# code: language=ansible
---

- name: "VRRP | Install | Apt"
  ansible.builtin.apt:
    name: "{{ vrrp_packages }}"
    state: "present"
    update_cache: false
    force_apt_get: true
    cache_valid_time: 3600
  become: true
  tags:
    - vrrp
    - vrrp-install
