# code: language=ansible
---

- name: "VRRP | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ vrrp_packages }}"
    state: "present"
    update_cache: false
  become: true
  tags:
    - vrrp
    - vrrp-install
